en:
  weight: 1
  languageName: English
zh:
  weight: 2
  languageName: 中文
  languagedirection: rtl
  # title: 
# fa:
#   weight: 2
#   languageName: فارسی
#   languagedirection: rtl
#   title: مهدی خوشنودی
