main:
  - weight: 1
    identifier: posts
    name: 博客
    url: /
  - weight: 2
    identifier: about
    name: 关于我
    url: /about/
  - weight: 3
    identifier: tags
    name: 附笺
    url: /tags/
  - weight: 4
    identifier: archives
    name: 归档
    url: /archives/
  - weight: 5
    identifier: search
    name: 搜索
    url: /search/
