main:
  - weight: 1
    identifier: home
    name: Home
    url: /
  - weight: 2
    identifier: about
    name: About
    url: /about/
  - weight: 3
    identifier: life
    name: Life
    url: /life/
  - weight: 4
    identifier: tags
    name: Tags
    url: /tags/
  - weight: 5
    identifier: archives
    name: Archives
    url: /archives/
  - weight: 6
    identifier: search
    name: Search
    url: /search/
  
