env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: Wenxuan Zhao
description: 
author: Wenxuan Zhao

rssFullContent: true

ShowReadingTime: true
ShowShareButtons: false
ShowCodeCopyButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
comments: true
defaultTheme: auto
disableSpecial1stPost: true
ShowToc: true
TocOpen: true
 

homeInfoParams:
  Title: Wenxuan Zhao
  Content:

socialIcons:
  # - name: twitter
  #   url: 
  # - name: stackoverflow
  #   url: 
  - name: github
    url: https://github.com/allanware
  - name: linkedin
    url: https://www.linkedin.com/in/allan-wenxuan-zhao
  - name: email
    url: mailto:xiaodoubizwx@gmail.com
