env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: Wenxuan Zhao
description: Passionate about software engineering, startups and leadership.
author: Mehdi Khoshnoodi

rssFullContent: true

images:
  - images/avatar.jpg

ShowReadingTime: true
ShowShareButtons: true
comments: true
defaultTheme: auto
disableSpecial1stPost: true

homeInfoParams:
  Title: Mehdi Khoshnoodi
  Content: Passionate about software engineering, startups and leadership.

socialIcons:
  # - name: twitter
  #   url: 
  # - name: stackoverflow
  #   url: 
  - name: github
    url: https://github.com/allanware
  - name: linkedin
    url: https://www.linkedin.com/in/allan-wenxuan-zhao
  - name: email
    url: mailto:xiaodoubizwx@gmail.com
