title: مهدی خوشنودی
description: پر شور و شوق در مورد مهندسی نرم‌افزار، استارتاپ‌ها و راهبری.
author: مهدی خوشنودی
homeInfoParams:
  Title: مهدی خوشنودی
  Content: پر شور و شوق در مورد مهندسی نرم‌افزار، استارتاپ‌ها و راهبری.
