title: 赵文轩
description: 足球, 电影, 巴萨, 计算机科学, 计算机, 博客, 生活, 美国, 围棋.
homeInfoParams:
  Content: > 
    在读计算机系研究生/博士。好像除了上一句以外再也想不到如何概括自己。不过也许标签贴得足够多就可以覆盖所有的标签。既然如此，何不给自己再贴多点标签呢。想要看更多我给自己贴的标签，请点[**关于我**](/zh/about/)；同时，我也会在[**碎片**](/zh/life/)里分享一些日常。点击[**附笺**](/zh/tags/)， 可以通过附笺来找到相关的文章；点击[**归档**](/zh/archives/)，可以看到编年式整理的所有过去的文章；最后，也可以[**搜索**](/zh/search)关键字来找到文章。

    - For English, please click [**En**](/).
