env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: Wenxuan Zhao
description: blog, life, Computer Science, Football, soccer, FC Barcelona, China, U.S., Go, Baduk, music, movie, film, book, classical music, concert
author: Wenxuan Zhao

ShowFullTextinRSS: true

ShowReadingTime: true
ShowShareButtons: false
ShowCodeCopyButtons: true
ShowPostNavLinks: true
ShowReadingTime: false
ShowBreadCrumbs: true
comments: true
defaultTheme: auto
disableSpecial1stPost: false
ShowToc: true
TocOpen: false
 
# the home page will only list pages from mainSections
mainSections:
  - posts

ShowRssButtonInSectionTermList: true

homeInfoParams: 
  Content: 
#socialIcons:
  # - name: twitter
  #   url: 
  # - name: stackoverflow
  #   url: 
  # - name: github
  #   url: https://github.com/allanware
  # - name: linkedin
  #   url: https://www.linkedin.com/in/allan-wenxuan-zhao
  # - name: email
  #   url: mailto:xiaodoubizwx@gmail.com
  # - name: RSS
  #   url: "index.xml"
  # - name: youtube 
  #   url:
  # - name: bilibili 
  #   url: 

assets:
  favicon: "/favicons/favicon.png"
  favicon16x16: "/favicons/favicon-16x16.png"
  favicon32x32: "/favicons/favicon-32x32.png"
  apple_touch_icon: "/favicons/apple-touch-icon.png"
  safari_pinned_tab: "/favicons/safari-pinned-tab.svg"